import 'package:flutter/material.dart';
import 'package:flutterapp/centralcamioneraapp/generatedmaskgroupwidget/generated/GeneratedPestaasWidget2.dart';

/* Group Mask Group
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMaskGroupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 50.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 50.0,
              child: GeneratedPestaasWidget2(),
            )
          ]),
    ));
  }
}
