import 'package:flutter/material.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedInfanteMenora2aosWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedAdultoMayorde13aosWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedPestaasWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedVectorWidget3.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedMenorDe2a12aosWidget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedVectorWidget2.dart';
import 'package:flutterapp/centralcamioneraapp/generatediniciowidget/generated/GeneratedBuscarWidget.dart';

/* Frame Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 609.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedPestaasWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 30.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 30.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 30.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 188.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 277.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedVectorWidget2(),
              ),
              Positioned(
                left: 275.0,
                top: 282.0,
                right: null,
                bottom: null,
                width: 20.45462989807129,
                height: 15.0,
                child: GeneratedVectorWidget3(),
              ),
              Positioned(
                left: 71.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 32.0,
                child: GeneratedAdultoMayorde13aosWidget(),
              ),
              Positioned(
                left: 71.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 32.0,
                child: GeneratedMenorDe2a12aosWidget(),
              ),
              Positioned(
                left: 71.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 32.0,
                child: GeneratedInfanteMenora2aosWidget(),
              ),
              Positioned(
                left: 199.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 29.0,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 201.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 29.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 201.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 29.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 90.0,
                top: 501.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 50.0,
                child: GeneratedBuscarWidget(),
              )
            ]),
      ),
    ));
  }
}
