import 'package:flutter/material.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget2/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget2/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget2/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget2/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget2/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget2/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/centralcamioneraapp/generatedboletosbaratoswidget2/generated/GeneratedPestaasWidget3.dart';

/* Frame Boletos baratos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBoletosbaratosWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 609.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedPestaasWidget3(),
              ),
              Positioned(
                left: 198.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 5.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 116.0,
                child: GeneratedGroup8Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 116.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 116.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 116.0,
                child: GeneratedGroup11Widget(),
              )
            ]),
      ),
    ));
  }
}
